# Generated by Django 5.2.4 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("degree", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("university", models.CharField(blank=True, max_length=100)),
                ("experience_1", models.TextField(blank=True)),
                ("experience_2", models.TextField(blank=True)),
                ("experience_3", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resume_pdf", models.FileField(blank=True, upload_to="resumes/")),
            ],
        ),
    ]
