# Generated by Django 5.2.4 on 2025-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='university',
            new_name='bachelor_university',
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='base',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='collaborated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_1_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_2_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_3_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_university',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phd_university',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
